CREATE TABLE matching_confirmation_sagas (
    id                          BIGINT         NOT NULL AUTO_INCREMENT,
    matching_id                 BIGINT         NOT NULL,
    status                      VARCHAR(20)    NOT NULL,
    attempt                     INT            NOT NULL,
    seat_reservation_command_id VARCHAR(36)    NOT NULL,
    payment_lock_command_id     VARCHAR(36)    NOT NULL,
    work_creation_command_id    VARCHAR(36)    NOT NULL,
    chat_creation_command_id    VARCHAR(36)    NOT NULL,
    seat_reservation_id         VARCHAR(100)   NULL,
    payment_id                  VARCHAR(100)   NULL,
    work_id                     VARCHAR(100)   NULL,
    chat_room_id                VARCHAR(100)   NULL,
    work_date                   DATE           NULL,
    start_time                  TIME(6)        NULL,
    end_time                    TIME(6)        NULL,
    locked_amount               DECIMAL(15, 2) NULL,
    currency                    VARCHAR(3)     NULL,
    seat_consumed               BOOLEAN        NOT NULL DEFAULT FALSE,
    failure_step                VARCHAR(30)    NULL,
    last_error                  VARCHAR(500)   NULL,
    lease_token                 VARCHAR(36)    NULL,
    lease_expires_at            DATETIME(6)    NULL,
    started_at                  DATETIME(6)    NOT NULL,
    completed_at                DATETIME(6)    NULL,
    version                     BIGINT         NOT NULL DEFAULT 0,
    created_at                  DATETIME(6)    NOT NULL,
    updated_at                  DATETIME(6)    NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_matching_confirmation_sagas_matching UNIQUE (matching_id),
    CONSTRAINT fk_matching_confirmation_sagas_matching
        FOREIGN KEY (matching_id) REFERENCES matchings (id)
        ON DELETE RESTRICT ON UPDATE RESTRICT,
    CONSTRAINT ck_matching_confirmation_sagas_status
        CHECK (status IN ('PROCESSING', 'COMPENSATING', 'COMPLETED', 'FAILED')),
    CONSTRAINT ck_matching_confirmation_sagas_attempt CHECK (attempt >= 1),
    CONSTRAINT ck_matching_confirmation_sagas_version CHECK (version >= 0),
    INDEX idx_matching_confirmation_sagas_status_lease (status, lease_expires_at, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
